// Copyright 2019 The OpenSDS Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

#ifndef _ENUM_DEFINE_H_
#define _ENUM_DEFINE_H_

/* Product model definition */
enum PRODUCT_MODE_E
{
    HUASY_V1500 = 0,
    HUASY_V1800,
    HUASY_S2100,
    HUASY_S2300,
    HUASY_S5100,
    HUASY_S5300,
    HUASY_S5500,
    HUASY_S5600,
    HUASY_VIS,
    HUASY_S2600,
    HUASY_S6800E,
    HUASY_V1500N,
    HUASY_S2300E,
    HUASY_COMMON,
    HUASY_N8000 = 15,
    HUASY_S6900,
    HUASY_S3900,
    HUASY_S5500T,
    HUASY_S5600T,
    HUASY_S6800T,
    HUASY_S6900_M100,
    HUASY_S3900_M200,
    HUASY_S3900_M300,
    HUASY_S5900_M100,
    HUASY_S8100,
    HUASY_S5800T,
    HUASY_V1600N,
    HUASY_S5900_M200,
    HUASY_N8001,
    HUASY_S2600T,
    HUASY_S8000_I,
    HUASY_SSS = 60,
    HUASY_VIS8200 = 800,
    HUASY_VIS8400,
    HUASY_VIS8600,
    HUASY_VIS8800
};

/* health status */
enum HEALTH_STATUS_E
{
    HEALTH_STATUS_UNKNOWN = 0,
    HEALTH_STATUS_NORMAL,
    HEALTH_STATUS_FAULT,
    HEALTH_STATUS_PREFAIL,
    HEALTH_STATUS_PARTBROKEN,
    HEALTH_STATUS_DEGRADE,
    HEALTH_STATUS_HASBADBLOCK,
    HEALTH_STATUS_HASERRORCODE,
    HEALTH_STATUS_CONSISTENT,
    HEALTH_STATUS_INCONSISTENT,
    HEALTH_STATUS_BUSY,
    HEALTH_STATUS_POWERNOINPUT,
    HEALTH_STATUS_POWERNOTENOUGH
};

/* running status */
enum RUNNING_STATUS_E
{
    RUNNING_STATUS_UNKNOWN = 0,    
    RUNNING_STATUS_NORMAL,
    RUNNING_STATUS_RUNNING,
    RUNNING_STATUS_NOTRUNNING,
    RUNNING_STATUS_NOTEXIST,
    RUNNING_STATUS_HIGHTEMPRATURESLEEP, 
    RUNNING_STATUS_STARTING,
    RUNNING_STATUS_POWERFAILUREPROTECTING,
    RUNNING_STATUS_SLEEPING,
    RUNNING_STATUS_SPINUP,
    RUNNING_STATUS_LINKUP,
    RUNNING_STATUS_LINKDOWN,
    RUNNING_STATUS_POWERON,
    RUNNING_STATUS_POWEROFF,
    RUNNING_STATUS_PRECOPY,
    RUNNING_STATUS_COPYBACK,
    RUNNING_STATUS_RECONSTRUCTION,
    RUNNING_STATUS_EXPANSION,
    RUNNING_STATUS_NOTFORMAT,
    RUNNING_STATUS_FORMATING,
    RUNNING_STATUS_UNMAPPING,
    RUNNING_STATUS_INITIALSYNC,
    RUNNING_STATUS_CONSISTENT,
    RUNNING_STATUS_SYNCHRONIZING,
    RUNNING_STATUS_SYNCHRONIZED,
    RUNNING_STATUS_NOTSYNCHRONIZED,
    RUNNING_STATUS_SPLIT,
    RUNNING_STATUS_ONLINE,
    RUNNING_STATUS_OFFLINE,
    RUNNING_STATUS_LOCKED,
    RUNNING_STATUS_ENABLED,
    RUNNING_STATUS_DISABLED,
    RUNNING_STATUS_LEVELING, 
    RUNNING_STATUS_TOBERECOVERD,
    RUNNING_STATUS_INTERRUPTED,
    
    RUNNING_STATUS_INVALID,
    RUNNING_STATUS_NOSTART,
    RUNNING_STATUS_QUEUING,
    RUNNING_STATUS_STOP,
    RUNNING_STATUS_COPYING,
    RUNNING_STATUS_COMPLETED,
    RUNNING_STATUS_PAUSE,
    RUNNING_STATUS_REVSYNCHRONIZING,
    RUNNING_STATUS_ACTIVATED,
    RUNNING_STATUS_ROLLBACK,
    RUNNING_STATUS_INACTIVATED,
    RUNNING_STATUS_IDLE,
    RUNNING_STATUS_POWERINGOFF,
    RUNNING_STATUS_CHARGING,
    RUNNING_STATUS_CHARGED,
    RUNNING_STATUS_TOBESYNCHRONIZED = 100,
    RUNNING_STATUS_ERROR           = 94
};

/* Association between two types of objects */
enum ASSOCIATE_TYPE_E
{
    ASSOCIATE_TYPE_MAPPING = 0    //mapping
};

/* Host operating system type */
enum OS_TYPE_E
{
    HOSTOS_LINUX = 0,
    HOSTOS_WINDOWS,
    HOSTOS_SOLARIS,
    HOSTOS_HPUX,
    HOSTOS_AIX,
    HOSTOS_XENSERVER,
    HOSTOS_MACOS,
    HOSTOS_ESX
};

/* Snapshot user */
enum SNAP_BELONG_E
{
    SNAPSHOT_PUBLIC = 1,
    SNAPSHOT_PRIVATE
};

/* Remote copy replication mode */
enum RM_MODEL_E
{
    RM_MODEL_SYNC = 1,      //Synchronous remote replication
    RM_MODEL_ASYNC          //Asynchronous remote replication
};

/* LUN relation type */
enum LUN_RELATION_E
{
    LUN_RELATION_MASTER = 1, //Primary LUN
    LUN_RELATION_SLAVE       //Slave LUN
};

/* Slave LUN data status*/
enum RM_LUN_MIRROR_STATE_E
{
    RM_LUN_MIRROR_STATE_SYNCED = 1,
    RM_LUN_MIRROR_STATE_CONSISTENT,
    RM_LUN_MIRROR_STATE_SYNCING,
    RM_LUN_MIRROR_STATE_INIT_SYNCING,
    RM_LUN_MIRROR_STATE_INCONSISTENT,
    RM_LUN_MIRROR_STATE_NOT_SYNC
};
/*HymperMetro LUN data status*/
enum RM_LUN_HM_STATE_E
{
    RM_LUN_HM_STATE_SYNCED = 1,
    RM_LUN_HM_STATE_CONSISTENT,
    RM_LUN_HM_STATE_SYNCING,
    RM_LUN_HM_STATE_INIT_SYNCING,
    RM_LUN_HM_STATE_INCONSISTENT,
    RM_LUN_HM_STATE_NOT_SYNC
};

/* the id of object in array */
enum OM_OBJ_E
{
    OBJ_DISK = 10,
    OBJ_LUN = 11,
    OBJ_HOSTGROUP = 14,
    OBJ_CPU = 16,
    OBJ_HOST = 21,
    OBJ_POWER = 23,
    OBJ_SNAPSHOT = 27,
    OBJ_REMOTEREPLICATION = 28,
    OBJ_FILESYSTEM = 40,
    OBJ_FSSNAPSHOT = 48,
    OBJ_SYSTEM = 201,
    OBJ_USER, 
    OBJ_DOMAIN,
    OBJ_DOMAINMEMBER,
    OBJ_BAY,
    OBJ_ENCLOSURE,
    OBJ_CONTROLLER,
    OBJ_EXPBOARD,
    OBJ_INTF_MODULE,
    OBJ_BACKUP_POWER,
    OBJ_FAN,
    OBJ_FC_PORT,
    OBJ_ETH_PORT,
    OBJ_SAS_PORT,
    OBJ_SERIAL_PORT,
    OBJ_STORAGEPOOL,
    OBJ_STORAGETIER,
    OBJ_SMARTCACHE,
    OBJ_LUNCOPY,
    OBJ_SPLITMIRROR,
    OBJ_CONSISTENTGROUP,
    OBJ_ISCSI_INITIATOR,
    OBJ_FC_INITIATOR,
    OBJ_REMOTE_DEVICE,
    OBJ_LINK,
    OBJ_REMOTEREPLICATIONMEMBERLUN,
    OBJ_LUNCOPYMEMBERLUN,
    OBJ_SPLITMIRRORTARGETLUN,
    OBJ_ISCSI_SESSION,
    OBJ_IOCLASS,
    OBJ_UPS,
    OBJ_PCIE_DATA_SWITCH,
    OBJ_PCIE_PORT,
    OBJ_SFP_OPTICAL_TRANSCEIVER,
    OBJ_BOND_PORT,
    OBJ_IPRule,
    OBJ_MEMORY,
    OBJ_LDAPCONFIG,
    OBJ_LDAPUSERMAP,
    OBJ_SNMPTRAPADDR,
    OBJ_SNMPCOMMUNITY,
    OBJ_SNMPUSM,
    OBJ_ISCSILINK,
    OBJ_LICENSE,
    OBJ_MAPPINGVIEW,

    OBJ_HOST_LINK = 255,
    OBJ_LUNGROUP = 256,
    OBJ_REPLICATIONPAIR = 263,
    OBJ_REPLICATIONVSTOREPAIR = 2000,
    OBJ_NFS_SHARE_AUTH_CLIENT = 16409,
    OBJ_HYPERMETROPAIR = 15361, 
    OBJ_HYPERMETRODOMAIN = 15362,
    OBJ_HYPERMETRO_CONSISTENTGROUP = 15364
};

//the read and write  status of slave LUN 
enum RESOURCE_ACCESS_E
{
    RESOURCE_ACCESS_NOACCESS = 1,
    RESOURCE_ACCESS_READ_ONLY,
    RESOURCE_ACCESS_READ_WRITE,
    RESOURCE_ACCESS_NODATA = 255
};

enum HCRESOURCETYPE_E
{
    HCRESOURCETYPE_LUN = 1,
    HCRESOURCETYPE_FS_E
};

enum LIF_ROLE_E
{
    MANAGEMENT_ROLE = 1,
    SERVICE_ROLE,
    MANAGEMENT_AND_SERVICE_ROLE
};

//Product model description
#define PRODUCT_MODEL_V1500             "V1500" 
#define PRODUCT_MODEL_V1800             "V1800"
#define PRODUCT_MODEL_S2100             "S2100"
#define PRODUCT_MODEL_S2300             "S2300"
#define PRODUCT_MODEL_S5100             "S5100"
#define PRODUCT_MODEL_S5300             "S5300"
#define PRODUCT_MODEL_S5500             "S5500"
#define PRODUCT_MODEL_S5600             "S5600"
#define PRODUCT_MODEL_VIS               "VIS6000"
#define PRODUCT_MODEL_S2600             "S2600"
#define PRODUCT_MODEL_S6800E            "S6800E"
#define PRODUCT_MODEL_V1500N            "V1500N"
#define PRODUCT_MODEL_S2300E            "S2300E"
#define PRODUCT_MODEL_COMMON            "COMMON"
#define PRODUCT_MODEL_S6900             "S6900"
#define PRODUCT_MODEL_S3900             "S3900"
#define PRODUCT_MODEL_S5500T            "S5500T"
#define PRODUCT_MODEL_S5600T            "S5600T"
#define PRODUCT_MODEL_S6800T            "S6800T"
#define PRODUCT_MODEL_S6900_M100        "S6900-M100"
#define PRODUCT_MODEL_S3900_M200        "S3900-M200"
#define PRODUCT_MODEL_S3900_M300        "S3900-M300"
#define PRODUCT_MODEL_S5900_M100        "S5900-M100"
#define PRODUCT_MODEL_S5800T            "S5800T"
#define PRODUCT_MODEL_S5900_M200        "S5900-M200"
#define PRODUCT_MODEL_N8000             "N8000"
#define PRODUCT_MODEL_N8001             "N8001"
#define PRODUCT_MODEL_S8001             "S8001"
#define PRODUCT_MODEL_S8100             "S8100"
#define PRODUCT_MODEL_S2600T            "S2600T"
#define PRODUCT_MODEL_SSS               "SSS"
#define PRODUCT_MODEL_S8000             "S8000-I"
#define PRODUCT_MODEL_V1600N            "V1600N"
#define PRODUCT_MODEL_VIS8200           "VIS8200"
#define PRODUCT_MODEL_VIS8400           "VIS8400"
#define PRODUCT_MODEL_VIS8600           "VIS8600"
#define PRODUCT_MODEL_VIS8800           "VIS8800"
#define PRODUCT_MODEL_DORADO_5000V3     805
#define PRODUCT_MODEL_DORADO_6000V3     806
#define PRODUCT_MODEL_DORADO_NAS        95
#define PRODUCT_VERSION_SUPPORT_CLONEFS "V300R006C00"
#define PRODUCT_VERSION_SUPPORT_CLONEFS_DORADO "V300R002C10"
#define PRODUCT_PATCH_SUPPORT_CLONEFS   "SPC100"

#define PRODUCT_MODEL_UNKOWN            "UNKOWN"

#endif 

